In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sleep.csv")

In [3]:
df

,body_weight,brain_weight,max_life_span,gestation_time,predation_index,sleep_exposure_index,danger_index,total_sleep
0,6654.000,5712.0,38.6,645,3,5,3,3.3
1,1.000,6.6,4.5,42,3,1,3,8.3
2,3.385,44.5,14,60,1,1,1,12.5
3,0.920,5.7,?,25,5,2,3,16.5
4,2547.000,4603.0,69,624,3,5,4,3.9
...,...,...,...,...,...,...,...,...
57,2.000,12.3,7.5,200,3,1,3,5.4
58,0.104,2.5,2.3,46,3,2,2,15.8
59,4.190,58.0,24,210,4,3,4,10.3
60,3.500,3.9,3,14,2,1,1,19.4
61,4.050,17.0,13,38,3,1,1,?

In [4]:
one = 1
two = 2
one + two

3

In [5]:
print(one)

1

In [6]:
print(one + two)

3

In [8]:
name = "Sara"
print(name)

Sara

In [9]:
cities = ["Chicago", "New York", "Dallas"]
cities

['Chicago', 'New York', 'Dallas']

In [10]:
cities[0]

'Chicago'

In [11]:
cities[:2]

['Chicago', 'New York']

In [12]:
cities[:3]

['Chicago', 'New York', 'Dallas']

In [14]:
cities[-1]

'Dallas'

In [19]:
print(cities[0],",", cities[2], sep="")

Chicago,Dallas

Dictionaries

In [22]:
city_populations = {
    "Dallas" : 1300000,
    "Chicago" : 2731585,
    "Austin" : 1054000
}

In [23]:
city_populations["Chicago"]

2731585

Dataframes

In [24]:
d = {
    "Books": [
        "Little Women",
        "In Limbo",
        "Eleven Birthdays",
        "Why Not Me?"
    ],
    "Words":[13000, 14000, 15000, 16000]

}
df = pd.DataFrame(d)
df

              Books  Words
0      Little Women  13000
1          In Limbo  14000
2  Eleven Birthdays  15000
3       Why Not Me?  16000

Inspecting a DataFrame

In [25]:
df.head(2)

          Books  Words
0  Little Women  13000
1      In Limbo  14000

In [26]:
df.info

<bound method DataFrame.info of               Books  Words
0      Little Women  13000
1          In Limbo  14000
2  Eleven Birthdays  15000
3       Why Not Me?  16000>

In [27]:
df.describe()

              Words
count      4.000000
mean   14500.000000
std     1290.994449
min    13000.000000
25%    13750.000000
50%    14500.000000
75%    15250.000000
max    16000.000000

In [28]:
df["Books"]

0        Little Women
1            In Limbo
2    Eleven Birthdays
3         Why Not Me?
Name: Books, dtype: object

In [30]:
df["Words"]

0    13000
1    14000
2    15000
3    16000
Name: Words, dtype: int64

In [31]:
df[:2]

          Books  Words
0  Little Women  13000
1      In Limbo  14000

Column and Row Selection

In [33]:
df["Books"][1:3]

1            In Limbo
2    Eleven Birthdays
Name: Books, dtype: object

In [35]:
total_words = df["Words"].sum()
total_words

np.int64(58000)

In [36]:
int(df["Words"].sum())

58000

In [39]:
avg_words = df["Words"].mean()
int(avg_words)

14500

In [40]:
max_words = df["Words"].max()
max_words

16000

In [43]:
df["Words"] > 14500
df[df["Words"] > 14500]

              Books  Words
2  Eleven Birthdays  15000
3       Why Not Me?  16000

String Contains

In [45]:
df[df["Books"].str.contains("ven")]

              Books  Words
2  Eleven Birthdays  15000

In [46]:
df[(df["Books"].str.contains("ven")) & (df["Words"] > 14500)]

              Books  Words
2  Eleven Birthdays  15000

Loops

In [47]:
for book in df["Books"]:
    print(book)

Little Women
In Limbo
Eleven Birthdays
Why Not Me?

In [48]:
for i in df["Books"]:
    print(i)

Little Women
In Limbo
Eleven Birthdays
Why Not Me?

Functions

In [51]:
def add_one(n):
    return n + 1

In [52]:
add_one(2)

3

In [53]:
chapters = [[0,1,'An Unexpected Party',8638,0],
            [0,2,'Roast Mutton',5257,0],
            [0,3,'A Short Rest',2876,0],
            [0,4,'Over Hill and Under Hill',4034,0],
            [0,5,'Riddles in the Dark',6967,0],
            [0,6,'Out of the Frying Pan into the Fire',6703,0],
            [0,7,'Queer Lodgings',9027,0],
            [0,8,'Flies and Spiders',10223,0],
            [0,9,'Barrels Out of Bond',5833,0],
            [0,10,'A Warm Welcome',3930,0],
            [0,11,'On the Doorstep',3001,0],
            [0,12,'Inside Information',7132,0],
            [0,13,'Not At Home',3909,0],
            [0,14,'Fire and Water',3236,0],
            [0,15,'The Gathering of the Clouds',3362,0],
            [0,16,'A Thief in the Night',2153,0],
            [0,17,'The Clouds Burst',3949,0],
            [0,18,'The Return Journey',2815,0],
            [0,19,'The Last Stage',2461,0],
            [1,-4,'Concerning Hobbits',3406,1],
            [1,-3,'Concerning Pipeweed',600,1], #This is a prologue
            [1,-2,'Of the Ordering of the Shire',2431,1],
            [1,-1,'Note on the Shire Records',914,1],
            [1,1,'A Long-expected Party',10012,1],
            [1,2,'The Shadow of the Past',11311,1],
            [1,3,'Three is Company',9763,1],
            [1,4,'A Short Cut to Mushrooms',5957,1],
            [1,5,'A Conspiracy Unmasked',5196,1],
            [1,6,'The Old Forest',6502,1],
            [1,7,'In the House of Tom Bombadil',5501,1],
            [1,8,'Fog on the Barrow-downs',6694,1],
            [1,9,'At the Sign of the Prancing Pony',6251,1],
            [1,10,'Strider',5905,1],
            [1,11,'A Knife in the Dark',9468,1],
            [1,12,'Flight to the Ford',8805,1],
            [1,1,'Many Meetings',9085,2],
            [1,2,'The Council of Elrond',16360,2],
            [1,3,'The Ring goes South',10656,2],
            [1,4,'A Journey in the Dark',11501,2],
            [1,5,'The Bridge of Khazad-dum',5428,2],
            [1,6,'Lothlorien',9387,2],
            [1,7,'The Mirror of Galadriel',6896,2],
            [1,8,'Farewell to Lorien',6174,2],
            [1,9,'The Great River',7218,2],
            [1,10,'The Breaking of the Fellowship',6305,2],
            [2,1,'The Departure of Boromir',3397,3],
            [2,2,'The Riders of Rohan',11133,3],
            [2,3,'The Uruk-hai',7854,3],
            [2,4,'Treebeard',12876,3],
            [2,5,'The White Rider',8856,3],
            [2,6,'The King of the Golden Hall',9303,3],
            [2,7,"Helm's Deep",7575,3],
            [2,8,'The Road to Isengard',7899,3],
            [2,9,'Flotsam and Jetsam',7789,3],
            [2,10,'The Voice of Saruman',5663,3],
            [2,11,'The Palantir',6325,3],
            [2,1,'The Taming of Smeagol',8375,4],
            [2,2,'The Passage of the Marshes',7357,4],
            [2,3,'The Black Gate is Closed',5881,4],
            [2,4,'Of Herbs and Stewed Rabbit',6975,4],
            [2,5,'The Window on the West',10120,4],
            [2,6,'The Forbidden Pool',5179,4],
            [2,7,'Journey to the Crossroads',4266,4],
            [2,8,'The Stairs of Cirith Ungol',6793,4],
            [2,9,"Shelob's Lair",5209,4],
            [2,10,'The Choices of Master Samwise',7322,4],
            [3,1,'Minas Tirith',13100,5],
            [3,2,'The Passing of the Grey Company',8586,5],
            [3,3,'The Muster of Rohan',6951,5],
            [3,4,'The Siege of Gondor',11793,5],
            [3,5,'The Ride of the Rohirrim',4358,5],
            [3,6,'The Battle of the Pelennor Fields',5225,5],
            [3,7,'The Pyre of Denethor',3736,5],
            [3,8,'The Houses of Healing',6731,5],
            [3,9,'The Last Debate',5416,5],
            [3,10,'The Black Gate Opens',5204,5],
            [3,1,'The Tower of Cirith Ungol',9721,6],
            [3,2,'The Land of Shadow',8446,6],
            [3,3,'Mount Doom',7777,6],
            [3,4,'The Field of Cormallen',4721,6],
            [3,5,'The Steward and the King',7639,6],
            [3,6,'Many Partings',7440,6],
            [3,7,'Homeward Bound',4106,6],
            [3,8,'The Scouring of the Shire',11296,6],
            [3,9,'The Grey Havens',4791,6]
           ]

In [ ]:
cols = ["CollectionNum", "ChapterNum", "ChapterName", "WordCount", "BookNum"]
data = pd.DataFrame(chapters,columns=cols)
data
#using chapters dictionary, assign cols to columns and makes a dataframe!

    CollectionNum  ChapterNum                ChapterName  WordCount  BookNum
0               0           1        An Unexpected Party       8638        0
1               0           2               Roast Mutton       5257        0
2               0           3               A Short Rest       2876        0
3               0           4   Over Hill and Under Hill       4034        0
4               0           5        Riddles in the Dark       6967        0
..            ...         ...                        ...        ...      ...
80              3           5   The Steward and the King       7639        6
81              3           6              Many Partings       7440        6
82              3           7             Homeward Bound       4106        6
83              3           8  The Scouring of the Shire      11296        6
84              3           9            The Grey Havens       4791        6

[85 rows x 5 columns]

Mapping Numbers to Names (CollectionNum Column)

In [55]:
title_map = {
    0: "The Hobbit",
    1: "The Fellowship of the Ring",
    2: "The Two Towers",
    3: "The Return of the King"
}

In [56]:
data["CollectionName"] = data["CollectionNum"].map(title_map)
data.head()

,CollectionNum,ChapterNum,ChapterName,WordCount,BookNum,CollectionName
0,0,1,An Unexpected Party,8638,0,The Hobbit
1,0,2,Roast Mutton,5257,0,The Hobbit
2,0,3,A Short Rest,2876,0,The Hobbit
3,0,4,Over Hill and Under Hill,4034,0,The Hobbit
4,0,5,Riddles in the Dark,6967,0,The Hobbit

In [61]:
data = data.drop(columns=["ChapterNum"])
data
#df = df.drop(columns=["Words"])

                  ChapterName  WordCount  BookNum          CollectionName
0         An Unexpected Party       8638        0              The Hobbit
1                Roast Mutton       5257        0              The Hobbit
2                A Short Rest       2876        0              The Hobbit
3    Over Hill and Under Hill       4034        0              The Hobbit
4         Riddles in the Dark       6967        0              The Hobbit
..                        ...        ...      ...                     ...
80   The Steward and the King       7639        6  The Return of the King
81              Many Partings       7440        6  The Return of the King
82             Homeward Bound       4106        6  The Return of the King
83  The Scouring of the Shire      11296        6  The Return of the King
84            The Grey Havens       4791        6  The Return of the King

[85 rows x 4 columns]

In [62]:
data.groupby("CollectionName").count()

                            ChapterName  WordCount  BookNum
CollectionName
The Fellowship of the Ring           26         26       26
The Hobbit                           19         19       19
The Return of the King               19         19       19
The Two Towers                       21         21       21

In [63]:
data.groupby("CollectionName").sum()

,ChapterName,WordCount,BookNum
CollectionName,,,
The Fellowship of the Ring,Concerning HobbitsConcerning PipeweedOf the Or...,187726,36
The Hobbit,An Unexpected PartyRoast MuttonA Short RestOve...,95506,0
The Return of the King,Minas TirithThe Passing of the Grey CompanyThe...,137037,104
The Two Towers,The Departure of BoromirThe Riders of RohanThe...,156147,73

In [64]:
data.groupby("CollectionName")["WordCount"].sum()

CollectionName
The Fellowship of the Ring    187726
The Hobbit                     95506
The Return of the King        137037
The Two Towers                156147
Name: WordCount, dtype: int64

In [65]:
data.groupby("CollectionName")["WordCount"].mean()

CollectionName
The Fellowship of the Ring    7220.230769
The Hobbit                    5026.631579
The Return of the King        7212.473684
The Two Towers                7435.571429
Name: WordCount, dtype: float64

In [66]:
dates = pd.DataFrame({
    'Books':df['Books'],
    'Year':[1977, 1937, 1954, 1955]
})
dates

              Books  Year
0      Little Women  1977
1          In Limbo  1937
2  Eleven Birthdays  1954
3       Why Not Me?  1955

Merge

In [70]:
merge = pd.merge(df, dates, on = "Books", how = 'inner')
merge
#how = inner means keep only rows that exist in both dataframes 
#on = Books means match rows with the same book name

              Books  Words  Year
0      Little Women  13000  1977
1          In Limbo  14000  1937
2  Eleven Birthdays  15000  1954
3       Why Not Me?  16000  1955